# Generated by Django 5.0.2 on 2026-01-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_description_property_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bhk_config',
            field=models.IntegerField(choices=[(1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4+ BHK'), (5, '5+ BHK')], default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('FLAT', 'Flat/Apartment'), ('VILLA', 'Villa/House'), ('LAND', 'Plot/Land'), ('STUDIO', 'Studio'), ('PENTHOUSE', 'Penthouse'), ('OFFICE', 'Office Space')], max_length=50),
        ),
    ]
