# Generated by Django 5.0.2 on 2026-01-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_bhk_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='doc_na_order',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/na_order/'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
    ]
