# Generated by Django 5.0.2 on 2026-01-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_doc_na_order_property_is_hot_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='doc_na_order',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_hot_deal',
        ),
    ]
