# Generated by Django 5.0.2 on 2026-01-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_doc_na_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk_config',
            field=models.IntegerField(blank=True, choices=[(1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4+ BHK')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpet_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('SALE', 'Sell'), ('RENT', 'Rent Out')], default='SALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('VILLA_BUNGALOW_ROWHOUSE', 'Villa / Bungalow / Rowhouse'), ('BUNGALOW_TWIN', 'Bungalow / Twin Bungalow'), ('FLAT_BHK', 'Flat (1bhk / 2 bhk / 3bhk)'), ('PLOT_RES_COMM', 'Plot / Residential / Commercial'), ('LAND_AGRI_IND', 'Land / Agriculture / Industrial'), ('SHOP_OFFICE_SHOWROOM', 'Shop / Office / Showroom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='super_builtup_area',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
