# Generated by Django 5.0.2 on 2026-01-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_building_commencement_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyfloorplan',
            options={'ordering': ['order', 'floor_number'], 'verbose_name': 'Floor Plan', 'verbose_name_plural': 'Floor Plans'},
        ),
        migrations.AddField(
            model_name='propertyfloorplan',
            name='floor_name',
            field=models.CharField(blank=True, help_text='Floor name/description', max_length=100),
        ),
        migrations.AddField(
            model_name='propertyfloorplan',
            name='floor_number',
            field=models.IntegerField(blank=True, help_text='Floor number (e.g., 0 for ground)', null=True),
        ),
        migrations.AddField(
            model_name='propertyfloorplan',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk_config',
            field=models.IntegerField(blank=True, choices=[(0, 'N/A'), (1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4+ BHK'), (5, '5+ BHK')], default=0, help_text='Number of bedrooms. Use 0 or N/A for plots/land/commercial properties.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_commencement_certificate',
            field=models.FileField(max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_completion_certificate',
            field=models.FileField(max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='doc_7_12_or_pr_card',
            field=models.FileField(max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gst_registration',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='layout_order',
            field=models.FileField(max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='layout_sanction',
            field=models.FileField(max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='mojani_nakasha',
            field=models.FileField(max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='na_order_or_gunthewari',
            field=models.FileField(max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rera_project_certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_deed_registration_copy',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_search_report',
            field=models.FileField(max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='propertyfloorplan',
            name='image',
            field=models.ImageField(max_length=255, upload_to='properties/floor_plans/'),
        ),
    ]
