# Generated by Django 5.0.2 on 2026-01-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_admin_notes_property_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electricity_bill',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_deed',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_commencement_certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_completion_certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='doc_7_12_or_pr_card',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='layout_order',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='layout_sanction',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='mojani_nakasha',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='na_order_or_gunthewari',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_search_report',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='properties/docs/'),
        ),
    ]
