# Generated by Django 5.0.2 on 2026-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_property_electricity_bill_property_sale_deed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Total number of views'),
        ),
    ]
