# Generated by Django 5.0.2 on 2026-01-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_kycverification_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='aadhaar_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhaar/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='aadhaar_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhaar/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('DIGILOCKER', 'DigiLocker'), ('AADHAAR_UPLOAD', 'Aadhaar Upload'), ('ADMIN', 'Admin Manual Verification')], max_length=20, null=True),
        ),
    ]
