# Generated by Django 5.0.2 on 2026-01-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_kycverification_aadhaar_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
