# Generated by Django 5.0.2 on 2026-01-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_kycverification_selfie_image_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('SELLER', 'Seller'), ('BUILDER', 'Builder'), ('BROKER', 'Real Estate Agent (Broker)'), ('PLOTTING_AGENCY', 'Plotting Company/Agency')], max_length=20, null=True),
        ),
    ]
