# Generated by Django 5.0.2 on 2026-02-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_externalapikey_delete_userapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalapikey',
            name='key',
        ),
        migrations.AddField(
            model_name='externalapikey',
            name='hashed_key',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='externalapikey',
            name='prefix',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
    ]
