# Generated by Django 5.0.2 on 2026-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_externalapikey_key_externalapikey_hashed_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapikey',
            name='hashed_key',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='externalapikey',
            name='prefix',
            field=models.CharField(default='', editable=False, max_length=8, unique=True),
        ),
    ]
