#!/bin/bash

# Diagnostic Script for Frontend Sync Issues
# Generated by Antigravity based on User Request

OUTPUT_FILE="frontend_diagnostic.txt"

echo "=== DIAGNOSTIC REPORT START: $(date) ===" > $OUTPUT_FILE

# Part 1: Verify Which File Is Being Used
echo "=== PART 1: SEARCHING FOR MARKETING PAGE FILES ===" >> $OUTPUT_FILE
echo "--- All Marketing Page Locations ---" >> $OUTPUT_FILE
find . -type f -name "page.tsx" -o -name "page.js" | grep marketing >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- App Router Marketing Files ---" >> $OUTPUT_FILE
find ./saudapakka_frontend/src/app -type d -name "marketing" >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Marketing Directory Contents ---" >> $OUTPUT_FILE
ls -la ./saudapakka_frontend/src/app/dashboard/my-listings/*/marketing/ >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "=== PART 1B: CURRENT FILE CONTENT ===" >> $OUTPUT_FILE
echo "--- First 50 Lines of Active File ---" >> $OUTPUT_FILE
cat ./saudapakka_frontend/src/app/dashboard/my-listings/[id]/marketing/page.tsx 2>/dev/null | head -n 50 >> $OUTPUT_FILE || echo "Cannot read file" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# Part 2: Check Docker Volume Mounts
echo "=== PART 2: DOCKER VOLUME MOUNT ANALYSIS ===" >> $OUTPUT_FILE
echo "--- Docker Compose Frontend Volumes ---" >> $OUTPUT_FILE
grep -A 10 "frontend:" docker-compose.yml | grep -A 5 "volumes:" >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Active Container Mounts ---" >> $OUTPUT_FILE
sudo docker inspect saudapakka_frontend --format='{{json .Mounts}}' | jq '.' >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- File Inside Container vs Host ---" >> $OUTPUT_FILE
echo "Host file timestamp:" >> $OUTPUT_FILE
ls -l ./saudapakka_frontend/src/app/dashboard/my-listings/[id]/marketing/page.tsx >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "Container file timestamp:" >> $OUTPUT_FILE
sudo docker exec saudapakka_frontend ls -l /app/src/app/dashboard/my-listings/[id]/marketing/page.tsx >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- File Content Hash Comparison ---" >> $OUTPUT_FILE
echo "Host file MD5:" >> $OUTPUT_FILE
md5sum ./saudapakka_frontend/src/app/dashboard/my-listings/[id]/marketing/page.tsx >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "Container file MD5:" >> $OUTPUT_FILE
sudo docker exec saudapakka_frontend md5sum /app/src/app/dashboard/my-listings/[id]/marketing/page.tsx >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

# Part 3: Check Next.js Build & Cache
echo "=== PART 3: NEXT.JS CACHE & BUILD STATUS ===" >> $OUTPUT_FILE
echo "--- .next Directory Status ---" >> $OUTPUT_FILE
ls -lah ./saudapakka_frontend/.next/ >> $OUTPUT_FILE 2>&1 || echo ".next directory not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Last Build Time ---" >> $OUTPUT_FILE
ls -ltr ./saudapakka_frontend/.next/ | tail -10 >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Standalone Output Check ---" >> $OUTPUT_FILE
ls -la ./saudapakka_frontend/.next/standalone >> $OUTPUT_FILE 2>&1 || echo "No standalone build" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== PART 3B: CONTAINER BUILD INFORMATION ===" >> $OUTPUT_FILE
echo "--- Container Image Info ---" >> $OUTPUT_FILE
sudo docker inspect saudapakka_frontend --format='{{.Created}}' >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Container Start Time ---" >> $OUTPUT_FILE
sudo docker inspect saudapakka_frontend --format='{{.State.StartedAt}}' >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Running Process in Container ---" >> $OUTPUT_FILE
sudo docker exec saudapakka_frontend ps aux >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Package.json Scripts ---" >> $OUTPUT_FILE
sudo docker exec saudapakka_frontend cat /app/package.json | jq '.scripts' >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

# Part 4: Check Frontend Logs
echo "=== PART 4: FRONTEND CONTAINER LOGS ===" >> $OUTPUT_FILE
echo "--- Last 200 Lines of Frontend Logs ---" >> $OUTPUT_FILE
sudo docker logs saudapakka_frontend --tail 200 >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Hot Reload Activity ---" >> $OUTPUT_FILE
sudo docker logs saudapakka_frontend 2>&1 | grep -i "compiled\|fast refresh\|hmr" | tail -20 >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# Part 5: Check Dockerfile & Configuration
echo "=== PART 5: DOCKERFILE CONFIGURATION ===" >> $OUTPUT_FILE
echo "--- Frontend Dockerfile ---" >> $OUTPUT_FILE
cat ./saudapakka_frontend/Dockerfile >> $OUTPUT_FILE 2>&1 || echo "Dockerfile not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Docker Compose Frontend Config ---" >> $OUTPUT_FILE
grep -A 30 "frontend:" docker-compose.yml >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

# Part 6: Test File Write & Hot Reload
echo "=== PART 6: FILE SYNC TEST ===" >> $OUTPUT_FILE
echo "--- Creating Test File on Host ---" >> $OUTPUT_FILE
TEST_FILE="./saudapakka_frontend/src/test_sync_$(date +%s).txt"
echo "// TEST FILE - $(date)" > "$TEST_FILE"
echo "Test file created at: $TEST_FILE" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Checking Test File in Container ---" >> $OUTPUT_FILE
sleep 2
sudo docker exec saudapakka_frontend ls -la "/app/src/${TEST_FILE##*/s}" 2>>$OUTPUT_FILE || sudo docker exec saudapakka_frontend ls -la "/app/src/$(basename $TEST_FILE)" >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

# Clean up
rm "$TEST_FILE" 2>/dev/null

# Part 8: Check Next.js Configuration
echo "=== PART 8: NEXT.JS CONFIGURATION ===" >> $OUTPUT_FILE
echo "--- next.config.ts/js Content ---" >> $OUTPUT_FILE
cat ./saudapakka_frontend/next.config.ts >> $OUTPUT_FILE 2>&1 || cat ./saudapakka_frontend/next.config.js >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

# Part 9: Environment Detection
echo "=== PART 9: ENVIRONMENT MODE ANALYSIS ===" >> $OUTPUT_FILE
echo "--- NODE_ENV in Container ---" >> $OUTPUT_FILE
sudo docker exec saudapakka_frontend env | grep NODE_ENV >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

# Part 10: Component Import Analysis
echo "=== PART 10: COMPONENT DEPENDENCY CHECK ===" >> $OUTPUT_FILE
echo "--- Import Statement in Marketing Page ---" >> $OUTPUT_FILE
grep -n "import.*MarketingCanvas" ./saudapakka_frontend/src/app/dashboard/my-listings/[id]/marketing/page.tsx >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Verify Component File Exists ---" >> $OUTPUT_FILE
ls -la ./saudapakka_frontend/src/components/marketing/MarketingCanvas* >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "=== DIAGNOSTIC COMPLETE ===" >> $OUTPUT_FILE
echo "Report generated at $OUTPUT_FILE"
