#!/bin/bash

# Diagnostic Report Generator for Saudapakka
# Generated by Antigravity

OUTPUT_FILE="diagnostic_report.txt"

echo "Starting diagnostic report generation..."
echo "Output will be saved to $OUTPUT_FILE"

# === Part 1: Environment Information ===
echo "=== SYSTEM INFORMATION ===" > $OUTPUT_FILE
echo "Date: $(date)" >> $OUTPUT_FILE
echo "OS: $(uname -a)" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== DOCKER VERSION ===" >> $OUTPUT_FILE
docker --version >> $OUTPUT_FILE
docker-compose --version >> $OUTPUT_FILE 2>/dev/null || docker compose version >> $OUTPUT_FILE 2>/dev/null
echo "" >> $OUTPUT_FILE

echo "=== NODE VERSION ===" >> $OUTPUT_FILE
node --version >> $OUTPUT_FILE 2>/dev/null || echo "Node not found locally" >> $OUTPUT_FILE
npm --version >> $OUTPUT_FILE 2>/dev/null || echo "Npm not found locally" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== PYTHON VERSION ===" >> $OUTPUT_FILE
python --version >> $OUTPUT_FILE 2>&1 || python3 --version >> $OUTPUT_FILE 2>&1 || echo "Python not found locally" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== DOCKER CONTAINERS ===" >> $OUTPUT_FILE
docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.Image}}" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== CONTAINER RESOURCE USAGE ===" >> $OUTPUT_FILE
docker stats --no-stream >> $OUTPUT_FILE 2>/dev/null
echo "" >> $OUTPUT_FILE

echo "=== DOCKER NETWORKS ===" >> $OUTPUT_FILE
docker network ls >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== NETWORK DETAILS (saudapkaa_mediakit_default) ===" >> $OUTPUT_FILE
docker network inspect saudapkaa_mediakit_default >> $OUTPUT_FILE 2>&1 || echo "Network not found (tried saudapkaa_mediakit_default)" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 2: Configuration Files Analysis ===
echo "=== DOCKER-COMPOSE.YML ===" >> $OUTPUT_FILE
cat docker-compose.yml >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== NEXT.CONFIG.TS/JS ===" >> $OUTPUT_FILE
cat saudapakka_frontend/next.config.ts >> $OUTPUT_FILE 2>&1 || cat saudapakka_frontend/next.config.js >> $OUTPUT_FILE 2>&1 || cat saudapakka_frontend/next.config.mjs >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== PACKAGE.JSON (frontend scripts) ===" >> $OUTPUT_FILE
cat saudapakka_frontend/package.json | jq '.scripts' >> $OUTPUT_FILE 2>&1 || grep -A 10 '"scripts"' saudapakka_frontend/package.json >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== FRONTEND ENV FILES ===" >> $OUTPUT_FILE
echo "--- .env.local ---" >> $OUTPUT_FILE
cat saudapakka_frontend/.env.local >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "--- .env ---" >> $OUTPUT_FILE
cat .env >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== AXIOS CONFIGURATION ===" >> $OUTPUT_FILE
echo "--- Looking for axios config files ---" >> $OUTPUT_FILE
find . -name "axios.ts" -o -name "axios.js" -o -name "api.ts" -o -name "api.js" | grep -v node_modules >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "--- lib/axios.ts content ---" >> $OUTPUT_FILE
cat saudapakka_frontend/src/lib/axios.ts >> $OUTPUT_FILE 2>&1 || cat saudapakka_frontend/lib/axios.ts >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== BACKEND CONFIGURATION ===" >> $OUTPUT_FILE
echo "--- Django settings.py (key sections) ---" >> $OUTPUT_FILE
# Using grep to find settings file location first
SETTINGS_FILE=$(find saudapakka_backend -name "settings.py" | head -n 1)
if [ -f "$SETTINGS_FILE" ]; then
    grep -A 5 "DATABASES" "$SETTINGS_FILE" >> $OUTPUT_FILE
    grep -A 10 "CORS" "$SETTINGS_FILE" >> $OUTPUT_FILE
    grep -A 5 "ALLOWED_HOSTS" "$SETTINGS_FILE" >> $OUTPUT_FILE
    grep -A 5 "MIDDLEWARE" "$SETTINGS_FILE" >> $OUTPUT_FILE
else
    echo "Settings file not found" >> $OUTPUT_FILE
fi
echo "" >> $OUTPUT_FILE

echo "--- Backend requirements.txt ---" >> $OUTPUT_FILE
cat saudapakka_backend/requirements.txt >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== BACKEND ENV FILES ===" >> $OUTPUT_FILE
echo "--- backend/.env ---" >> $OUTPUT_FILE
cat saudapakka_backend/.env >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== NGINX CONFIGURATION ===" >> $OUTPUT_FILE
cat nginx.conf >> $OUTPUT_FILE 2>&1 || cat nginx/nginx.conf >> $OUTPUT_FILE 2>&1 || cat nginx/default.conf >> $OUTPUT_FILE 2>&1 || echo "File not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 3: Network Connectivity Tests ===
echo "=== NETWORK CONNECTIVITY TESTS ===" >> $OUTPUT_FILE
echo "Test Date: $(date)" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Test 1: Frontend (Port 3010) ---" >> $OUTPUT_FILE
echo "Command: curl -I http://localhost:3010/" >> $OUTPUT_FILE
curl -I http://localhost:3010/ >> $OUTPUT_FILE 2>&1
echo "Exit Code: $?" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Test 2: Backend Direct (Port 8005 mapped to 8000) ---" >> $OUTPUT_FILE
# Adjusted to 8005 based on previous knowledge of docker-compose.dev.yml
echo "Command: curl -I http://localhost:8005/api/" >> $OUTPUT_FILE
curl -I http://localhost:8005/api/ >> $OUTPUT_FILE 2>&1
echo "Exit Code: $?" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Test 3: Nginx (Port 80) ---" >> $OUTPUT_FILE
echo "Command: curl -I http://localhost/" >> $OUTPUT_FILE
curl -I http://localhost/ >> $OUTPUT_FILE 2>&1
echo "Exit Code: $?" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Test 4: API through Nginx ---" >> $OUTPUT_FILE
echo "Command: curl -I http://localhost/api/" >> $OUTPUT_FILE
curl -I http://localhost/api/ >> $OUTPUT_FILE 2>&1
echo "Exit Code: $?" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Test 5: Health Check ---" >> $OUTPUT_FILE
echo "Command: curl http://localhost:8005/health/" >> $OUTPUT_FILE
curl http://localhost:8005/health/ >> $OUTPUT_FILE 2>&1
echo "Exit Code: $?" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Test 6: Login Endpoint Structure ---" >> $OUTPUT_FILE
echo "Command: curl -X OPTIONS http://localhost:8005/api/auth/login/" >> $OUTPUT_FILE
curl -X OPTIONS http://localhost:8005/api/auth/login/ -v >> $OUTPUT_FILE 2>&1
echo "Exit Code: $?" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Test 7: CORS Headers Check ---" >> $OUTPUT_FILE
echo "Command: curl with Origin header" >> $OUTPUT_FILE
curl -I -H "Origin: http://localhost:3010" http://localhost:8005/api/ >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== DNS & NETWORK RESOLUTION ===" >> $OUTPUT_FILE
echo "--- Localhost Resolution ---" >> $OUTPUT_FILE
ping -c 3 localhost >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- 127.0.0.1 Resolution ---" >> $OUTPUT_FILE
ping -c 3 127.0.0.1 >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Open Ports (netstat) ---" >> $OUTPUT_FILE
sudo netstat -tuln | grep -E ':(80|3000|3010|8000|8005|5432)' >> $OUTPUT_FILE 2>&1 || sudo ss -tuln | grep -E ':(80|3000|3010|8000|8005|5432)' >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 4: Container Logs ===
echo "=== CONTAINER LOGS ===" >> $OUTPUT_FILE
echo "Captured at: $(date)" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- FRONTEND LOGS (last 100 lines) ---" >> $OUTPUT_FILE
sudo docker logs saudapakka_frontend --tail 100 >> $OUTPUT_FILE 2>&1 || echo "Container not running" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- BACKEND LOGS (last 100 lines) ---" >> $OUTPUT_FILE
sudo docker logs saudapakka_backend --tail 100 >> $OUTPUT_FILE 2>&1 || echo "Container not running" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- NGINX LOGS (last 100 lines) ---" >> $OUTPUT_FILE
sudo docker logs saudapakka_nginx --tail 100 >> $OUTPUT_FILE 2>&1 || echo "Container not running" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- DATABASE LOGS (last 50 lines) ---" >> $OUTPUT_FILE
sudo docker logs saudapakka_stable_postgres --tail 50 >> $OUTPUT_FILE 2>&1 || echo "Database container not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 5: Backend Deep Dive ===
echo "=== DJANGO APPLICATION STATUS ===" >> $OUTPUT_FILE
# Using the correct container name 'saudapakka_backend'
sudo docker exec saudapakka_backend bash -c "
echo '--- Django Check ---'
python manage.py check 2>&1

echo ''
echo '--- Migration Status ---'
python manage.py showmigrations 2>&1

echo ''
echo '--- Installed Apps ---'
python manage.py diffsettings 2>&1 | grep INSTALLED_APPS -A 20

echo ''
echo '--- Available URLs ---'
# show_urls handles might not exist, but let's try
python manage.py show_urls 2>&1 || echo 'show_urls not available'

echo ''
echo '--- Database Connection Test ---'
python manage.py shell -c \"from django.db import connection; connection.ensure_connection(); print('Database: Connected')\" 2>&1
" >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== BACKEND FILE STRUCTURE ===" >> $OUTPUT_FILE
tree -L 3 saudapakka_backend/ >> $OUTPUT_FILE 2>&1 || find saudapakka_backend/ -maxdepth 3 -type f -name "*.py" >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 6: Frontend Deep Dive ===
echo "=== FRONTEND BUILD STATUS ===" >> $OUTPUT_FILE
echo "--- .next Directory ---" >> $OUTPUT_FILE
ls -la saudapakka_frontend/.next/ >> $OUTPUT_FILE 2>&1 || echo ".next directory not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- node_modules Status ---" >> $OUTPUT_FILE
ls -la saudapakka_frontend/node_modules/ | head -n 20 >> $OUTPUT_FILE 2>&1 || echo "node_modules not found" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== FRONTEND FILE STRUCTURE ===" >> $OUTPUT_FILE
tree -L 3 -I 'node_modules|.next' saudapakka_frontend/ >> $OUTPUT_FILE 2>&1 || find saudapakka_frontend/ -maxdepth 3 -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \) | grep -v node_modules | grep -v .next >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 7: Browser Console Logs (Placeholders) ===
echo "=== BROWSER CONSOLE ANALYSIS ===" >> $OUTPUT_FILE
echo "[MANUAL STEP REQUIRED - See User Instructions]" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 8: Specific Error Recreation ===
echo "=== LOGIN ENDPOINT TEST ===" >> $OUTPUT_FILE
echo "--- Test 1: Login with test credentials ---" >> $OUTPUT_FILE
curl -X POST http://localhost:8005/api/auth/login/ \
  -H "Content-Type: application/json" \
  -d '{"email":"test@example.com"}' \
  -v >> $OUTPUT_FILE 2>&1 # Changed username to email based on previous context
echo "" >> $OUTPUT_FILE

echo "--- Test 2: Login with empty payload ---" >> $OUTPUT_FILE
curl -X POST http://localhost:8005/api/auth/login/ \
  -H "Content-Type: application/json" \
  -d '{}' \
  -v >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Test 3: OPTIONS (CORS Preflight) ---" >> $OUTPUT_FILE
curl -X OPTIONS http://localhost:8005/api/auth/login/ \
  -H "Origin: http://localhost:3010" \
  -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: Content-Type" \
  -v >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 9: Database Analysis ===
echo "=== DATABASE ANALYSIS ===" >> $OUTPUT_FILE
echo "--- Database Container Status ---" >> $OUTPUT_FILE
sudo docker ps | grep -E 'postgres|mysql|mongo|db' >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Database Connection Test (dbshell) ---" >> $OUTPUT_FILE
# Adjusting to use specific container name and assuming postgres
sudo docker exec saudapakka_backend python manage.py dbshell --command="SELECT 1;" >> $OUTPUT_FILE 2>&1 || echo "Could not connect via dbshell" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Django Tables ---" >> $OUTPUT_FILE
sudo docker exec saudapakka_backend python manage.py shell -c "
from django.core.management import call_command
from django.apps import apps
for model in apps.get_models():
    print(f'{model._meta.db_table}')
" >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# === Part 10: Security & Permissions ===
echo "=== FILE PERMISSIONS ===" >> $OUTPUT_FILE
echo "--- Backend Directory Permissions ---" >> $OUTPUT_FILE
ls -la saudapakka_backend/ >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Frontend Directory Permissions ---" >> $OUTPUT_FILE
ls -la saudapakka_frontend/ | grep -E 'src|components|lib|app' >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== ENVIRONMENT VARIABLES ===" >> $OUTPUT_FILE
echo "--- Frontend Container Env ---" >> $OUTPUT_FILE
sudo docker exec saudapakka_frontend env | grep -E 'NODE_ENV|API|NEXT' >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE

echo "--- Backend Container Env ---" >> $OUTPUT_FILE
sudo docker exec saudapakka_backend env | grep -E 'DJANGO|DEBUG|DATABASE|CORS|ALLOWED' >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "=== DIAGNOSTIC SUMMARY ===" >> $OUTPUT_FILE
echo "Generated: $(date)" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Quick Status Overview ---" >> $OUTPUT_FILE
echo "Frontend Container: $(sudo docker ps | grep saudapakka_frontend > /dev/null && echo 'Running' || echo 'Stopped')" >> $OUTPUT_FILE
echo "Backend Container: $(sudo docker ps | grep saudapakka_backend > /dev/null && echo 'Running' || echo 'Stopped')" >> $OUTPUT_FILE
echo "Nginx Container: $(sudo docker ps | grep saudapakka_nginx > /dev/null && echo 'Running' || echo 'Stopped')" >> $OUTPUT_FILE
echo "Database Container: $(sudo docker ps | grep saudapakka_stable_postgres > /dev/null && echo 'Running' || echo 'Stopped')" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

echo "--- Port Accessibility ---" >> $OUTPUT_FILE
curl -s -o /dev/null -w "Port 3010 (Frontend): %{http_code}\n" http://localhost:3010/ >> $OUTPUT_FILE 2>&1
curl -s -o /dev/null -w "Port 8005 (Backend): %{http_code}\n" http://localhost:8005/api/ >> $OUTPUT_FILE 2>&1
curl -s -o /dev/null -w "Port 80 (Nginx): %{http_code}\n" http://localhost/ >> $OUTPUT_FILE 2>&1
echo "" >> $OUTPUT_FILE
echo "===================" >> $OUTPUT_FILE

echo "✅ Diagnostic report generated at $OUTPUT_FILE"
